/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ExperienceRaizRouteImport } from './routes/experience/raiz'
import { Route as ExperienceMandiriRouteImport } from './routes/experience/mandiri'
import { Route as ExperienceEdotRouteImport } from './routes/experience/edot'
import { Route as ExperienceConsistechRouteImport } from './routes/experience/consistech'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRaizRoute = ExperienceRaizRouteImport.update({
  id: '/experience/raiz',
  path: '/experience/raiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceMandiriRoute = ExperienceMandiriRouteImport.update({
  id: '/experience/mandiri',
  path: '/experience/mandiri',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceEdotRoute = ExperienceEdotRouteImport.update({
  id: '/experience/edot',
  path: '/experience/edot',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceConsistechRoute = ExperienceConsistechRouteImport.update({
  id: '/experience/consistech',
  path: '/experience/consistech',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience/consistech': typeof ExperienceConsistechRoute
  '/experience/edot': typeof ExperienceEdotRoute
  '/experience/mandiri': typeof ExperienceMandiriRoute
  '/experience/raiz': typeof ExperienceRaizRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience/consistech': typeof ExperienceConsistechRoute
  '/experience/edot': typeof ExperienceEdotRoute
  '/experience/mandiri': typeof ExperienceMandiriRoute
  '/experience/raiz': typeof ExperienceRaizRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/experience/consistech': typeof ExperienceConsistechRoute
  '/experience/edot': typeof ExperienceEdotRoute
  '/experience/mandiri': typeof ExperienceMandiriRoute
  '/experience/raiz': typeof ExperienceRaizRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/experience/consistech'
    | '/experience/edot'
    | '/experience/mandiri'
    | '/experience/raiz'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experience/consistech'
    | '/experience/edot'
    | '/experience/mandiri'
    | '/experience/raiz'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/experience/consistech'
    | '/experience/edot'
    | '/experience/mandiri'
    | '/experience/raiz'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceConsistechRoute: typeof ExperienceConsistechRoute
  ExperienceEdotRoute: typeof ExperienceEdotRoute
  ExperienceMandiriRoute: typeof ExperienceMandiriRoute
  ExperienceRaizRoute: typeof ExperienceRaizRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/raiz': {
      id: '/experience/raiz'
      path: '/experience/raiz'
      fullPath: '/experience/raiz'
      preLoaderRoute: typeof ExperienceRaizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/mandiri': {
      id: '/experience/mandiri'
      path: '/experience/mandiri'
      fullPath: '/experience/mandiri'
      preLoaderRoute: typeof ExperienceMandiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/edot': {
      id: '/experience/edot'
      path: '/experience/edot'
      fullPath: '/experience/edot'
      preLoaderRoute: typeof ExperienceEdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/consistech': {
      id: '/experience/consistech'
      path: '/experience/consistech'
      fullPath: '/experience/consistech'
      preLoaderRoute: typeof ExperienceConsistechRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceConsistechRoute: ExperienceConsistechRoute,
  ExperienceEdotRoute: ExperienceEdotRoute,
  ExperienceMandiriRoute: ExperienceMandiriRoute,
  ExperienceRaizRoute: ExperienceRaizRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
